### ISSUE TITLE
Drop Grunt for 1.0.0?

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#11]
In the rewrite (#5), the user is given the option to choose a build system: Grunt or npm. This sets up an identical workflow with either tool (and npm aliases in the case of Grunt).

However, I'm wondering, why offer Grunt at all? The only benefit I see is that it provides choice. But its drawbacks are significantly more complex code, maintenance, and testing.

I propose we do npm only with the standards documentation indicating that it's fine for developers to create their own build process aliased behind npm scripts with standard names.

**Comment by gkatsev** [comment]
:+1: from me. What would the version of this be once we merge your PR?

**Comment by misteroneill** [comment]
I think 1.0.0.

I'd like to get that merged shortly after we're all back from the holiday.

**Comment by gkatsev** [comment]
Since we already have the grunt support, what about just releasing what we have as 1.0 and then remove it and release 2.0?

**Comment by misteroneill** [comment]
For one, because I already stripped it out in a PR just now: #12 :smile:

**Comment by gkatsev** [comment]
I guess that's fine.
