### ISSUE TITLE
default root-based urls make it hard to use with gh-pages

### ISSUE THREAD

**Issue by gkatsev** [videojs/generator-videojs-plugin#115]
The [default index.html](https://github.com/videojs/generator-videojs-plugin/blob/master/generators/app/templates/_index.html) file uses root-relative urls for all the js and other inclusion. This means that this page can't be displayed properly with a standard static file server in a directory above it. Also, makes it hard being able to re-use that example for gh-pages.

**Comment by misteroneill** [comment]
Fixed by #118
