### ISSUE TITLE
Freshly Generated Plugin Has 404 Errors

### ISSUE THREAD

**Issue by johndanek** [videojs/generator-videojs-plugin#117]
I noticed that the plugin was updated recently, and doesn't seem to work like it once did. I installed a new blank plugin, selected Y for all of the options. When I run `npm start` none of the videojs assets are correctly loaded. For example, it's trying to load video-js.css from `http://localhost:9999/node_modules/videojs-spellbook/node_modules/video.js/dist/video-js.css` but that 404s. Same with video.js.

A previous version of this plugin I used included a lot more in package.json, and I believe it all worked out of the box. What has to be done to get everything working?

**Comment by misteroneill** [comment]
Thanks for the report, we've noticed this internally, too. Fix is coming shortly!

**Comment by misteroneill** [comment]
In the meantime, if you remove the `videojs-spellbook/node_modules/` bit from your paths in the generated `index.html` file, you should be good to go.
