### ISSUE TITLE
Add sub generators for common subclass-able elements

### ISSUE THREAD

**Issue by hartman** [videojs/generator-videojs-plugin#15]
See for instance: https://github.com/yeoman/generator-angular

They could be:
yo videojs:component
yo videojs:tech
yo videojs:sourcehandler

etc. each generating a new named boilertemplate implementation of these in ./src, and adding an import statement etc.

**Comment by misteroneill** [comment]
Still interested in doing this for sure, but we are taking things in a _slightly_ different (and, we think, better) direction with the generator by abstracting out a lot of its commonalities. This should make the generator more lightweight and make running it all the time to get updates should be rarer.

**Comment by misteroneill** [comment]
Don't think this is going to happen, honestly.
