### ISSUE TITLE
Rethink how plugin packaged files are determined?

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#18]
Right now, the files that end up in a plugin package on npm are determined, essentially, by including everything that's not filtered out by `.npmignore`.

I don't think this is a _bad_ way to do it, but it does allow for the possibility that files could get included in a package implicitly. For example, we had an issue with a plugin where Sublime Text project file(s) were included because they were not ignored by the `.npmignore` file.

The alternative approach is to have an empty `.npmignore` file, which means nothing is excluded, but use the `"files"` array of `package.json` to explicitly declare what gets included in a package. Ultimately, I think this makes a bit more sense.

**Comment by misteroneill** [comment]
This may be worth including in #16

**Comment by gkatsev** [comment]
Only issue I have with that is that then you can get into things like https://github.com/sass/node-sass/issues/1183 where you end up with things not getting packaged up

**Comment by misteroneill** [comment]
That's true. No matter what you do, there's going to be a limitation.

I like the idea of a package only including what it _explicitly_ needs - rather than just including everything by default. The node-sass issue seems pretty edge-casey to me (where you'd want something packed, but not on npm), where the issue of things being included that don't need to be seems more common.

**Comment by gkatsev** [comment]
Yeah, it's probably ok. Just want our initial rules to be general enough so that we don't get into situations like that easily.

**Comment by misteroneill** [comment]
Ok, I think we have a consensus path forward in PR #16
