### ISSUE TITLE
Package.json file missing when generating new advanced /basic plugin

### ISSUE THREAD

**Issue by swaraasolutions** [videojs/generator-videojs-plugin#187]
Hi,

I started creating a fresh plugin by following the guides however, as soon as the plugin is generated in the folder i noticed there is a package.lock file but the package.json file is missing due to which it is hard to do npm install is it something i am missing?

Thanks for your help in advance
![videojs-bug](https://user-images.githubusercontent.com/12116208/41933192-ca05276e-79a0-11e8-8c35-bfaabc477a8b.png)

![folderstructure](https://user-images.githubusercontent.com/12116208/41933245-f03ba796-79a0-11e8-80cb-48cace2583fd.png)

**Comment by gkatsev** [comment]
Thanks for the issue, it should be fixed when we get this PR in: https://github.com/videojs/generator-videojs-plugin/pull/185/files#r198185122

**Comment by swaraasolutions** [comment]
Thanks very much for an extremely fast response any ideas when this PR will be available?

Thanks

**Comment by gkatsev** [comment]
should be soon, reviewing it currently.
