### ISSUE TITLE
No local grunt installation

### ISSUE THREAD

**Issue by Soviut** [videojs/generator-videojs-plugin#2]
Windows 10
node 4.1.2
npm 3.3.8
yo 1.4.8

After running the generator I decided to run grunt to see what the build process was like. I went into the project folder and typed `grunt` but got the "not installed" error.

```bash
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project.
```

I made sure grunt was installed globally with `npm install -g grunt grunt-cli` but then noticed the mention of "locally" in the message. So I just did `npm install grunt` and it worked.

The generated package.json should be updated to include this dependency.

**Comment by misteroneill** [comment]
Closed by #3
