### ISSUE TITLE
Ordering of name, description, version, main is moved when using the generator

### ISSUE THREAD

**Issue by gkatsev** [videojs/generator-videojs-plugin#26]
The order of those 4 fields should stay the same/at the top of the package.json file.

**Comment by gkatsev** [comment]
We should switch to using [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) so that the items stay in the same place and don't move.

**Comment by misteroneill** [comment]
:+1:

**Comment by misteroneill** [comment]
Also, I noticed that this isn't properly merging properties from the current package.json into the new one - whoops!

**Comment by misteroneill** [comment]
Looks like the use of `JSON.stringify` is buried in Yeoman somewhere. No worries: I'll just work around Yeoman. :+1:
