### ISSUE TITLE
Don't wrap the code in the index.html in an iife

### ISSUE THREAD

**Issue by gkatsev** [videojs/generator-videojs-plugin#27]
I think it's better to not wrap the [code in the index.html](https://github.com/videojs/generator-videojs-plugin/blob/e23339ce64629d9620ade173fe4180015e028082/src/app/templates/_index.html#L23-L26) in na IIFE. That example page is often used as a playground as well and having the player variable set globally is useful because you can just open the page and in the dev tools, you already have a variable called `player` that's all set up and ready to go.

**Comment by misteroneill** [comment]
The `player` is explicitly exposed `var player = window.player = ...` for that very purpose. The IIFE is there for any other private variables that someone may or may not want to create there.

**Comment by gkatsev** [comment]
Oh. I totally missed that. I guess it's fine then. I'll close for now and maybe re-open if I find a good usecase for this.
