### ISSUE TITLE
Cannot use 'in' operator to search for 'Buffer' in undefined

### ISSUE THREAD

**Issue by samueleastdev** [videojs/generator-videojs-plugin#292]
Hi,

I am trying to update this plugin https://github.com/chemoish/videojs-bif that uses jDataView to analyze a bif image.

But I keep running into this error.

src: https://github.com/jDataView/jDataView/blob/master/dist/jdataview.js

Cannot use 'in' operator to search for 'Buffer' in undefined
In jDataView it is stopping at this line.

NodeBuffer: !0 && "Buffer" in global,
Seems to be an issue with the global.

You can see the file that calls the jDataView here.

https://github.com/chemoish/videojs-bif/blob/master/src/parser.js

It works on the old version but not the latest one I am just a bit confused with how to resolve this error been stuck on it for a while now.

Maybe it has something to do with the way the new video-js plugin generator is setup https://github.com/videojs/generator-videojs-plugin

Not sure any help would be appreciated thanks.

**Comment by Kamyil** [comment]
Hi @samueleastdev !
During migrating very legacy project from Webpack to Vite, I also ran into this issue. Do you remember maybe why was it closed as completed?
