### ISSUE TITLE
Not compatible with videoJS 5.0

### ISSUE THREAD

**Issue by Soviut** [videojs/generator-videojs-plugin#4]
The package.json currently points to video.js 4.5 for both devDependencies and peerDependencies.

Additionally, `mergeOptions()` is no longer kept under `videojs.util`, so the following line

https://github.com/dmlap/generator-videojs-plugin/blob/master/app/templates/_videojs-plugin.js#L17
```javascript
    var settings = videojs.util.mergeOptions(defaults, options),
        player = this;
```
Should be
```javascript
    var settings = videojs.mergeOptions(defaults, options),
        player = this;
```

**Comment by misteroneill** [comment]
We are currently working on a rewrite of this project; so, I don't think adding video.js 5.x compatibility makes sense on the 0.1.x line. The next major version - 1.0.0, which I expect to be ready this month - should be compatible with video.js 5.

In the meantime, users can use the [videojs-4to5](https://github.com/videojs/videojs-4to5) tool to either update their code or use the included plugin to monkey patch 4.x compatibility into a video.js 5.x environment.
