### ISSUE TITLE
Support scoped packages

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#40]
At Brightcove, we use scoped npm packages. We should have a prompt (and a `--bcov` default) for this possibility.

**Comment by gkatsev** [comment]
I would prefer a more generic approach to scoped packages.

**Comment by misteroneill** [comment]
How much more generic can you get than a prompt asking for an npm package scope?

The `--bcov` thing would only be setting this value automatically.

**Comment by gkatsev** [comment]
Oh, I misread. I thought you said only `--bcov`.
I'm not sure that I would want brightcove-specific stuff in here if we can avoid it.

**Comment by misteroneill** [comment]
Fair enough. It can be removed easily for 2.0.
