### ISSUE TITLE
create a module for common tasks

### ISSUE THREAD

**Issue by gkatsev** [videojs/generator-videojs-plugin#42]
we should break out the various common tasks the generator currently adds files for into a separate module that can just be auto-added as a dev dependency.
This way, it'll be easier to get updates for various changes to builds and what not.

**Comment by misteroneill** [comment]
You mean like the contents of `scripts/`?

**Comment by gkatsev** [comment]
Yep, `scripts/` and whatever else.

**Comment by gkatsev** [comment]
This will turn into the [spellbook](https://github.com/videojs/spellbook)

**Comment by misteroneill** [comment]
Since this has a direction and it's in another repo, I'll close this. There will be a future PR to use Spellbook.
