### ISSUE TITLE
Update .travis.yml to use 4.3 instead of 4.2

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#56]

**Comment by gkatsev** [comment]
I think `argon` maybe be a tag for LTS. Or maybe `LTS` will work better. Finding the correct label for it would be nicer than just using a version number for it.

**Comment by misteroneill** [comment]
Agreed. I'll look into that.

**Comment by misteroneill** [comment]
Doesn't seem to be a tag for LTS. Will just bump to 4.4.

**Comment by gkatsev** [comment]
it's coming to nvm soon.

**Comment by misteroneill** [comment]
Fixed in #65
