### ISSUE TITLE
Unable to install as documented

### ISSUE THREAD

**Issue by acpmasquerade** [videojs/generator-videojs-plugin#61]
$ yo videojs-plugin
```
Error videojs-plugin 
You don't seem to have a generator with the name videojs-plugin installed.
```

$ yo generator-videojs-plugin
```
Error generator-videojs-plugin 
You don't seem to have a generator with the name generator-videojs-plugin installed.
```

installed version
│ ├─┬ yeoman-generator@0.20.3
...
├─┬ generator-videojs-plugin@2.0.0

**Comment by gkatsev** [comment]
Installation happens via `npm` like how `yo` gets installed itself.
You can [install it](https://github.com/videojs/generator-videojs-plugin#getting-started) by running
```sh
$ npm install -g generator-videojs-plugin
```
Afterwards, you can run it by running `yo`:
```sh
$ yo videojs-plugin
```
Hope that helps.

**Comment by acpmasquerade** [comment]
$npm ls -g yo yeoman-generato
```
├─┬ generator-videojs-plugin@2.0.0
│ └── yeoman-generator@0.20.3 
└── yo@1.7.0 
```
Required packages are installed.

And the output submitted was after the necessary packages were installed.

**Comment by gkatsev** [comment]
@misteroneill thoughts?

**Comment by misteroneill** [comment]
I have the same versions and it works for me. What happens if you run `yo --generators` to list your generators?
