### ISSUE TITLE
Test files are being uploaded to npm

### ISSUE THREAD

**Issue by forbesjo** [videojs/generator-videojs-plugin#62]
See https://github.com/videojs/generator-videojs-plugin/blob/master/src/app/package-json.js#L200. Should just the `dist/` and `es5/` folder be uploaded to npm?

**Comment by gkatsev** [comment]
yes, they should all be included. The tarball from npm isn't what you should be deploying to production.

**Comment by gkatsev** [comment]
We probably shouldn't be publishing dist/test, though.

**Comment by forbesjo** [comment]
Why not exclude files that a user will never use?

**Comment by misteroneill** [comment]
@gkatsev and I have discussed this several times before and I'm still not convinced that we should be sending anything more than the minimum up to npm. That said... it's not _harmful_.

**Comment by misteroneill** [comment]
Honestly, I'm inclined to say we should only publish what would need to be used rather than anything. I haven't yet heard an argument for including everything that I find convincing.

**Comment by gkatsev** [comment]
I still feel that we should publish everything except things that are definitely not necessary on npm like travis.yml and gitignore.
However, I'm not so strongly for it so that if others feel like it's not necessary, it can be changed.

**Comment by BrandonOCasey** [comment]
I think that src should be published as well, so that es6 code can be used by other es6 code with es6 build tools (where possible)

**Comment by misteroneill** [comment]
Alright, I think my position on this currently is that we ought to limit our publishing to `dist/`, `es5/`, and `src/`.

**Comment by BrandonOCasey** [comment]
maybe docs too, although I don't think we have any handling for that atm?
