### ISSUE TITLE
Bannerize does not handle SASS generated BOM char

### ISSUE THREAD

**Issue by hartman** [videojs/generator-videojs-plugin#63]
SASS outputs a BOM (\ufeff) character at the start of the generated files. Bannerize does not take this into account and just puts bytes in front of the BOM char. You then have a BOM char in the middle of the file, which is an invalid CSS file, that is ignored by (some? at least Chrome) browsers.

**Comment by misteroneill** [comment]
@hartman Ah, interesting, thanks for the report! Would you mind re-creating the issue in [misteroneill/bannerize](https://github.com/misteroneill/bannerize/issues), since that's where it'd need fixing? Thanks again!

**Comment by hartman** [comment]
Upstream misteroneill/bannerize#3
