### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#7]
Support Windows. Work is ongoing in #33

In the generator itself:

- [x] `"prebuild"`
- [x] `"build:generator:copy"`
- [x] ~~`vjsplugin`~~ Removed.

In generated projects:

- [x] `"mkdirs"`
- [x] `"clean"`
- [x] `"build:test:browserify"`
- [x] `"build:css:sass"`
- [x] `"docs"`
- [x] `"watch:css"`
- [x] `"watch:test"`
- [x] ~~`scripts/npm-preversion-for-bower.sh`~~ Removed.
- [x] `scripts/npm-version-for-bower.js` Renamed.
- [x] `scripts/npm-postversion-for-bower.js` Renamed.

**Comment by elmosgot** [comment]
Do you need any help in this part?

**Executing mkdir script"
mkdir -p dist dist-test es5
This runs the first time properly, but creates also a folder called '-p'. The second run this fails and makes the 'watch' script crash.

**Generating the CSS file:**
The main problem I have found is that 'mv' is not found. I tried adding a mv.bat file inside C:\Windows\System32, but that triggered another error related to the relative paths.

**Quick solution**
Changed the following:
"mkdirs": "mkdir -p dist dist-test es5", => "mkdirs": "mkdir dist dist-test es5",

And removed it from the 'watch' script:
"watch": "npm run mkdirs && npm-run-all -p watch:*", => "watch": "npm-run-all -p watch:*",

I haven't found yet a solution for renaming the plugin.css into the plugin name

**Comment by misteroneill** [comment]
@elmosgot Thanks for the feedback! 

The issue here is a mis-match between the Windows commands and the *nix commands. I don't think there's a nice way to solve this by altering the `"scripts"` in `package.json`.

I was planning on using `shelljs` to handle these commands across platforms in small `.js` scripts. If you'd like to take a stab at that, it'd be appreciated for sure! If not, I am planning to get to the 1.1.0 task(s) before the New Year.

**Comment by misteroneill** [comment]
Part of the problem with that approach is that there isn't a great solution right now for using `shelljs` from the command line or npm scripts (without writing actual script files for simple things).

**Comment by misteroneill** [comment]
It looks like we could use `mkdirp` and `rimraf` for the `"mkdirs"` and `"clean"` scripts respectively, but there's still no good solution for the `"build:test:browserify"` task because:

1. Windows lacks a `find` command that works like *nix.
1. Browserify doesn't support glob patterns as an entry point, which I think is dumb.
1. Browserify doesn't accept `stdin` as input for entry points.

Or for the `"build:css:sass"` command because Windows lacks a `mv` command and there doesn't appear to be a good cross-platform Node-based solution.

The alternative is to write actual `.js` scripts for these, which is not terribly palatable. At that point, why not just take advantage of a tool like Grunt or Gulp? Which, unfortunately, may be the path forward to get cross-platform support.

**Comment by misteroneill** [comment]
After discussion, I think this is - for now - going to have to be a stand-alone script solution for the few places that Windows needs special treatment. It's not ideal, but it'll work.

Also, I threw around the idea of a meta-project, `videojs-plugin-builder` that abstracts away a lot of this stuff.

**Comment by elmosgot** [comment]
Sorry I was busy last weeks let me see if I can come up with a nice solution using shelljs or anything else I find on the road.

Anyway Happy 2016!

**Comment by gkatsev** [comment]
@elmosgot check out #33 so that we don't repeat work :)

**Comment by elmosgot** [comment]
Ok will do
