### ISSUE TITLE
Load test dependancies from one location

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/generator-videojs-plugin#74]
## Problem

Right now it's very awkward to edit tests dependancies as they are stored in two places, it would be really nice to load them all from the same place to prevent errors in one or the other. (test/index.html vs karma config)
## Solutions
1. Use karma's builtin server/watch/debug functionality on `start` so that we don't have to maintain test builds
2. Inject dependancies in the karma config into the `test/index.html` file using another build step
## Choice

I think that we should really investigate number one as it will make this whole project simpler if we can get it to work and we won't have to maintain any test html or test build ourselves.
## Implementation
- proxy karma's debug page to the current `:9999/test` route so that everything is seemless
- use https://github.com/karma-runner/karma-qunit/pull/41 to show the qunit UI when it is merged
- configure `npm run start` and other applicable commands to do `karma start test/karma.conf.js --no-single-run`
- change the karma configuration file so that it allows command line overrides IE `singleRun: config.singleRun || false`
- configure karma to run on watch with `autoWatch` set to true, so we can auto re-run tests

**Comment by misteroneill** [comment]
Sounds like a great idea - I'm all for it.

**Comment by gkatsev** [comment]
I think I would prefer doing the reverse of that if anything. Generate the test file separately use that bundle in `test/index.html` and karma.
Also, this ties in with https://github.com/videojs/video.js/issues/3543, where maybe the place where we put the test files isn't the ideal location for how we build and test our code.

**Comment by misteroneill** [comment]
If I'm understanding correctly, that's kinda what it does now: we have `test/dist/bundle.js` that includes the tests and source in one big package.

I think @dmlap didn't like that because we're not testing the `dist/videojs-foo.js` file, rather a compilation specific to tests, which seems like a fair point to me.

**Comment by BrandonOCasey** [comment]
I think that we still want to do this so that we don't have a silly `test/index.html` which has to copy all of the files from `test/karma.conf.js` verbatim

**Comment by misteroneill** [comment]
What about those of us who like to load their tests in the browser without all that Karma nonsense!? 😉

**Comment by BrandonOCasey** [comment]
haha well you won't even need to know about karma
