### ISSUE TITLE
Switch to using yoman to manage dependencies, rather than hardcoding versions

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/generator-videojs-plugin#82]
http://yeoman.io/authoring/dependencies.html

This will keep us from worrying about keeping packages up to date, and we will just force old versions when we need to, rather than forcing old version by default.

**Comment by misteroneill** [comment]
I guess my concern with that is that it's a little too loose without providing at least a major version number for each package. And, if we did that, we are sort of losing the point of removing those changes from the `package-json.js` script.

Also, there are uses of the generator (e.g. `--hurry`, `--skip-install`) that would prevent the `package.json` from having dependencies updated. The idea with those options is that the user can run `npm install` as needed _after_ the generator updates their `package.json`.

**Comment by BrandonOCasey** [comment]
makes sense
