### ISSUE TITLE
rename main file from plugin.js to index.js

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/generator-videojs-plugin#84]
plugin.js kind of makes sense, but index.js makes it way easier to work with the main source file of a plugin by only having to refer to the top level directory, and index.js is used much more often for node.js projects (it's usually index.js or the projects name as the main file)

Example

``` JavaScript
// if the file is `src/index.js' we can now require the plugin by referencing 
require('src');
```

**Comment by misteroneill** [comment]
I'm fine with renaming `src/plugin.js` to `src/index.js`.

That said, `"main"` should still point to `es5/index.js` or `lib/index.js` (it might make sense to rename it) because it should point to the Babel output, so others can use the plugin via Node/Browserify without needing Babel.

**Comment by BrandonOCasey** [comment]
yeah I agree it should point to `es5/index.js` rather than `src/index.js` since we want to point to the es5 version
